### PR TITLE
NYT-clone-page-1

### PR DESCRIPTION
**Pull request by John-Arboleda**
# Pull Request of Webpage from The New York Times

> This pull request is a clone of The New York Times article [Space Ripples Reveal Big Bang’s Smoking Gun](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)  as an exercise for **Layout**, **Flexbox**, and **Grid**.

- Semantic HTML tags (article, aside, section, footer, figure, figcaption) are used.
- Flexbox containers can be found on the top navbar, article sections, main-footer.
- Grid containers were implemented for the explanation of the "Inflation Theory" figure, both Editors' Picks sections (aside and footer navbar), and suggested content tables and links.
- All the main content has a fixed width. Media Queries were not applied.
- The New York Times have their own personalized fonts. The content is displayed using a similar font.

### CODE REVIEW

**Review by LamiaSristy — COMMENTED** [review]
# Status: Invalid Review Request ✖️ 🔴
Hello Team!! ✋

**Unfortunately, I have to mark this review request as invalid. 😢**

# Reasons:

## You have submitted the wrong link to PR, You need to submit the PR link, not the `pull/1/commits`.

## According to rules, all your GitHub Actions checks need to be successful, to be a valid CRR.

**Two of your GitHub Actions Linters checks were not successful. Which are:**
* `Linters / Webhint`
* `Linters / Stylelint`

Please fix the linters errors at your project and then ask again for a CRR.

Feel free to reach me on slack @LamiaSristy 🙋

Keep up the spirit always. Happy Coding 💻

**Review by SmithVyne — CHANGES_REQUESTED** [review]
Invalid Pull Request 🤒 ❌ 
Please make your pull request title and description more professional.
Try to describe the changes you made. Describe what this pull request does. Make these changes and submit them for another code review.

You can also reach out to me on slack, @SmithVyne if you have any other questions.

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @John-Arboleda    ! :wave: :wave:

#### You have done well so far, I had to take a second look cause your project looks almost exactly like the actual site!  :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.
- - -

### **Recommended**

**General**
- [ ] Just as the previous TSEs have stated, you have to write a descriptive Pull Request Message with a descriptive title as well. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information.

**Section Specific requirements**
- [ ] **You are missing certain parts of your project which includes:** 

- [ ] **The `social media row and comments` section.**
**Original**
Screenshot (85)

- [ ] **The `Suggested News Letter and Most Popular` sections.**
**Original**

Screenshot (87)

- [ ] **The More in `Space and Astronomy` section.**
**Original**

Screenshot (88)

- [ ]  **The `Editor's Picks` section.**

**Original**

Screenshot (89)

- [ ] **The footer.**
 **Original**

Screenshot (90)

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 

Great job @John-Arboleda, and thanks for making the required changes :hammer: :wrench:.

Now you can merge, your project is approved :checkered_flag: 

## Happy Coding :tophat:

**Comment by John-Arboleda** [comment]
Thank you very much

**Pull request merged**
